### ISSUE TITLE
Add support for multiple wordlists at a time in comma delimited format

### ISSUE THREAD

**Issue by codingo** [codingo/VHostScan#1]
At present scanning class supports a single wordlist with 

> vhostscan -w wordlist.txt

 Issue raises the need for:

> vhostscan -w wordlist.txt, hostnamelist.txt

Etc'

**Comment by tizz98** [comment]
@codingo I can work on this one if it hasn't started to be worked on yet

**Comment by codingo** [comment]
@tizz98 No work on this yet, you're more than welcome :)

**Comment by tizz98** [comment]
I think I have this wrapped up, will PR on Oct 1! Happy Hacktoberfest!

**Comment by codingo** [comment]
Closed with #46
