### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by sky-code** [codingo/VHostScan#100]
rename ```NUM_INSTALLED``` to ```num_installed```

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    '' if num_installed else 'numpy==1.12.0'],
NameError: name 'num_installed' is not defined
```
https://github.com/natrix-fork/VHostScan/blob/master/setup.py#L15

https://github.com/natrix-fork/VHostScan/blob/master/setup.py#L38

**Comment by codingo** [comment]
Easy change, going to shelve for HacktoberFest since it's not far away and will help people  to get a run on the board. Feel free to contribute back yourself or dm me on twitter (@codingo_) if you would like some help to do so.

**Comment by konstunn** [comment]
@codingo, got a fix. Should this issue be closed?

**Comment by sky-code** [comment]
yep, fixed, issue should be closed.
