### ISSUE TITLE
Add setup file

### ISSUE THREAD

**Issue by codingo** [codingo/VHostScan#16]
Add setup file to add application to $PATH and install dependancies

**Comment by MohitS10** [comment]
Hi. Can i work on this?

**Comment by codingo** [comment]
Definitely @MohitS10.

**Comment by codingo** [comment]
Hi @MohitS10! How'd you go with this?

**Comment by MohitS10** [comment]
Hi! So i think i have managed to write a setup script that installs the dependencies. Its a simple setup function from the setuptools library. I have no idea what you mean by adding application to $PATH. Do you mean to add the path of the script to the $PATH environment variable?

**Comment by codingo** [comment]
Yup! I believe aetuptools will handle that but don't know for sure. I can test in a vm for you if you want to pr what you already have and then we can adjust from there?

**Comment by MohitS10** [comment]
Sure! I'll PR by tonight.

**Comment by codingo** [comment]
Change for this has now moved to #83

**Comment by codingo** [comment]
Closed with #83
