### ISSUE TITLE
Optional flag to cease scan on first 200 response for CTF items?

### ISSUE THREAD

**Issue by codingo** [codingo/VHostScan#20]
Although in a commercial setting catch-all's are quite likely this doesn't always appear to be the case in CTF items. In these cases you don't need vhostscan's catch-all/likepage filtering and instead would want to know about the first 200 response code found.

Potentially there's some value in a flag that will stop the scan and surface results on the first 200 response code that's hit? It's a minor item since they would find the content with a full scan anyway, but one to consider.

**Comment by prabhath6** [comment]
If i understand correctly, this should return first likepage which matches the given target host. So typically it would output two results, one being the actual host and the other one will be the file likepage.

**Comment by codingo** [comment]
@prabhath6 Yup, that's the one. Are you tackling it?

**Comment by prabhath6** [comment]
yep, can you assign me this task. So i tried running this in windows there was issue in the some file which 
 is using both tabs and space i will push a fix for that too.
One last this to confirm if user wish to write the results to file, there should only be 2 entries in the file one being the actual and other being the first match.

**Comment by codingo** [comment]
Great! I think master already has the first issue resolved - I've pushed about four pr's in the last three days. You should be able to merge it back over ok.

And yup, in this case the output would automatically work since you would be popping out of the routine early (and subsequently not adding on output).

**Comment by prabhath6** [comment]
okay, i will pull in latest changes and push out the change.

**Comment by codingo** [comment]
Resolved in #63
