### ISSUE TITLE
Fix formatting on Json Output

### ISSUE THREAD

**Issue by codingo** [codingo/VHostScan#54]
We now have working json output but it's all on one line. I resolved this in a prior project (https://github.com/codingo/Ransomware-Json-Dataset) however I think it was a different library, simplejson. It may be solvable in the current implementation without adding new dependencies (current implementation is quite clean and shouldn't be rewritten). Merits investigation to see if cleanly formatted json can be outputted without a rewrite..

**Comment by schedutron** [comment]
Can I work on this?

**Comment by codingo** [comment]
Sure thing!

**Comment by xuvez** [comment]
Hi @schedutron check this: https://docs.python.org/2/library/json.html#basic-usage
At the "indent" parameter
