### ISSUE TITLE
Create a CI recipe for the project

### ISSUE THREAD

**Issue by diogoosorio** [codingo/VHostScan#56]
I've just opened a PR that [introduces some tests to the project](#55).

The next step would be to make sure that the test battery is run every time a PR is opened. A CI (continuous integration) system is great for automating this kind of job.

[Tracis CI](https://travis-ci.org) appears to be the de-facto service for this kind of work in the Github/open source community.

I'm up for writing the recipe for the system (for now to run the test battery each time a PR is opened), but the task would then require for a maintainer to open up an account on Travis CI (so that it would be associated with this repository).

Is this something worth pursuing? What are your thoughts about this?

**Comment by codingo** [comment]
@diogoosorio Definitely interested in this. I've linked this on Travis CI and @ufocoder has done some work writing this up but it looks to be in error at the moment (see #58 for log)

Definitely would love if you can do the final push for this!

**Comment by codingo** [comment]
#58 is now resolved with #59 but would definitely appreciate assistance wiring in your test cases!

**Comment by diogoosorio** [comment]
@ufocoder did include running the test suite as one of the integration validations. You can see them [running on this job](https://travis-ci.org/codingo/VHostScan/jobs/284303241#L483), for example.

I'm going to close this issue. :tada:

**Comment by codingo** [comment]
My sincere apologies @ufocoder, this is definitely my bad. I'm still quite new to continuous integration cases within python. Appreciate all that you both do for this project!
