### ISSUE TITLE
Automated test case (requirements) is failing

### ISSUE THREAD

**Issue by codingo** [codingo/VHostScan#58]
#57 introduced automated test cases but one of these appears to be failing. Despite the correct Python version appearing to be used the numpy install is complaining about it:

> $ python --version
> Python 3.2.6
> $ pip --version
> pip 7.1.2 from /home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages (python 3.2)
> 3.24s$ pip install -r ./requirements.txt
> Collecting dnspython==1.15.0 (from -r ./requirements.txt (line 1))
>   Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
>     100% |████████████████████████████████| 180kB 1.8MB/s 
> Collecting fuzzywuzzy==0.15.1 (from -r ./requirements.txt (line 2))
>   Downloading fuzzywuzzy-0.15.1-py2.py3-none-any.whl
> Collecting numpy==1.12.0 (from -r ./requirements.txt (line 3))
>   Downloading numpy-1.12.0.zip (4.8MB)
>     100% |████████████████████████████████| 4.8MB 101kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "/tmp/pip-build-qtb0e3/numpy/setup.py", line 34, in <module>
>         raise RuntimeError("Python version 2.7 or >= 3.4 required.")
>     RuntimeError: Python version 2.7 or >= 3.4 required.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qtb0e3/numpy

**Comment by arpitx165** [comment]
@codingo I have fixed travis build issue.Can you check my pull request

**Comment by codingo** [comment]
Looks good. Since there's another ticket to wire in the other tests I'll close this issue off.
