### ISSUE TITLE
Apply PEP 8 conventions to the codebase

### ISSUE THREAD

**Issue by diogoosorio** [codingo/VHostScan#61]
So the codebase is still small enough for us to retrofit [PEP 8](https://www.python.org/dev/peps/pep-0008/) style convention.

The [CI recipe is already running a linter to enforce the coding style](https://github.com/codingo/VHostScan/blob/master/.travis.yml), but a bunch of rules are being silenced because the project doesn't currently follow those conventions.

@codingo would this be something worth pursuing? Would it be acceptable to open a PR to make sure that makes the linter happy, or is this a too big of a change to be done in single passage/PR?

**Comment by codingo** [comment]
Sorry for the slow reply @diogoosorio I've been finishing an engagement. And I Definitely agree with this. A large driver for this project for me was to learn more about Python and the standards surrounding it to help boost my knowledge as I rewrite NoSQLMap. Anything learnt here has benefits outside of it.

I've found a few linters that seem reasonable and I've been reading up more about pep8 so I'll put some time into this tomorrow. Any pull request in this area is more than welcome!

**Comment by diogoosorio** [comment]
The CI recipe already has a linting tool (validates that pep8 is enforced in the codebase), but its current configuration omits a number of warnings (because the codebase doesn't adhere to them, thus the CI build would always fail).

If you're OK with this direction, I'll give it a go (as the codebase is still small, I believe I'll be able to do it in one sitting). :+1:

**Comment by codingo** [comment]
Sure thing. Totally ok with anything that makes the project better!

**Comment by codingo** [comment]
Resolved with #65
