### ISSUE TITLE
ImportError: No module named queue :: Recommendation

### ISSUE THREAD

**Issue by moorer2k** [codingo/VHostScan#78]
Did some research on this specific error, and I simply did as people were saying to do:

Change:
 from queue import Queue 
To:
from multiprocessing import Queue

 Apparently it gets confused. Works now!

**Comment by codingo** [comment]
Are you sure you're in the right repo? We don't have threading yet - were you adding it?

**Comment by moorer2k** [comment]
Yeah I had two projects open, narcolepsy will do that to you. Brain dead all the time haha. It was for AWSBucketDump :P

**Comment by codingo** [comment]
No worries! Just making sure no outstanding help needed before leaving this one :)
