### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by infosecsecurity** [codingo/VHostScan#86]
Getting this error when trying to run VHostScan

![screenshot from 2018-03-20 19-13-03](https://user-images.githubusercontent.com/7826342/37685638-efa766d8-2c72-11e8-9056-46d520bf61bf.png)

**Comment by infosecsecurity** [comment]
I already ran the python setup.py install but it didn't help

**Comment by codingo** [comment]
Since you've run setup.py you should be able to run it directly. Instead of:

```
$ python VHostScan.py <params>
```

It should work with just:

```
VHostscan <params>
```

The method you're using bypasses the package setup. Could you please try this and reopen this issue if you have any remaining issues?
