### ISSUE TITLE
output files implicit local directory

### ISSUE THREAD

**Issue by linted** [codingo/VHostScan#88]
## When specifying an output file with a flag like -oN, the local directory should be implicitly used
Right now you have to manually add the `./` before your output file name if you want it to be in the current directory. If you don't, an exception is thrown and no output file is written.

## Check to make sure that directory is not empty before trying to stat/make it
This can easily be achieved by adding an if statement around the try/execpt block on line 18 of `file_helper.py`. Another option if you assume that most people will be outputing to another dir is to wrap the `mkdir()` call on line 21 with a similar if statement

**Comment by codingo** [comment]
Closed with #89
