### ISSUE TITLE
Import error when running vhostscan

### ISSUE THREAD

**Issue by C-fire** [codingo/VHostScan#96]
vhostscan gives an import error when executed
* Installation method (git clone): python setup.py install
* Client OS: Linux loki 4.16.0-kali2-amd64 #1 SMP Debian 4.16.16-2kali2 (2018-07-04) x86_64 GNU/Linux
* Program version (see banner): VHostScan 1.21
* Relevant console output (if any):
**Traceback (most recent call last):
File "./vhostscan.py", line 8, in <module>
from .lib.core.virtual_host_scanner import *
ValueError: Attempted relative import in non-package**

**Comment by codingo** [comment]
@C-fire sorry I missed this in the fray. You need to run setup, the instructions can be found in README.md of this repository.
