### ISSUE TITLE
i have allready package and why error again????

### ISSUE THREAD

**Issue by harriseka** [codingo/VHostScan#99]
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
/usr/local/lib/python3.6/dist-packages/fuzzywuzzy-0.15.1-py3.6.egg/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
+-+-+-+-+-+-+-+-+-+  v. 1.21
|V|H|o|s|t|S|c|a|n|  Developed by @codingo_ & @__timk
+-+-+-+-+-+-+-+-+-+  https://github.com/codingo/VHostScan

usage: VHostScan [-h] -t TARGET_HOSTS [-w WORDLISTS] [-b BASE_HOST] [-p PORT]
                 [--prefix PREFIX] [--suffix SUFFIX] [-r REAL_PORT]
                 [--ignore-http-codes IGNORE_HTTP_CODES]
                 [--ignore-content-length IGNORE_CONTENT_LENGTH] [--first-hit]
                 [--unique-depth UNIQUE_DEPTH] [--ssl] [--fuzzy-logic]
                 [--no-lookups] [--rate-limit RATE_LIMIT] [--waf] [-v]
                 [-oN OUTPUT_NORMAL | -oJ OUTPUT_JSON | -oG OUTPUT_GREPABLE]
                 [--random-agent | --user-agent USER_AGENT]
VHostScan: error: the following arguments are required: -t

**Comment by codingo** [comment]
Looks like not much detail here, I'm unsure how to help you.

Based on the above you haven't passed a target to the application (using -t). Is there something further to this I'm missing and if so could you please provide a bit more detail?

**Comment by harriseka** [comment]
even though I use VHostScan -t it still appears that error like that and I also totally deleted my linux times (4.17.0-times1-amd64 # 1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU / Linux )

**Comment by codingo** [comment]
Could you please copy the whole output of the terminal window here (including the flags you're using to launch VHostScan). I'm assuming you ran setup.py also?

**Comment by harriseka** [comment]
root@harris:~/GitHub/VHostScan# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    '' if num_installed else 'numpy==1.12.0'],
NameError: name 'num_installed' is not defined
root@harris:~/GitHub/VHostScan# pip install -r requirements.txt 
Collecting dnspython==1.15.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a6/72/209e18bdfedfd78c6994e9ec96981624a5ad7738524dd474237268422cb8/dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 732kB/s 
Collecting fuzzywuzzy==0.15.1 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/d4/b9/2f883a23ca6a843cbd25e3ac9d625de4fecf830c4a08979a528b1a3354a8/fuzzywuzzy-0.15.1-py2.py3-none-any.whl
Collecting numpy==1.12.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/cb/47/19e96945ee6012459e85f87728633f05b1e8791677ae64370d16ac4c849e/numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 1.2MB/s 
Requirement already satisfied: pandas==0.19.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.19.2)
Collecting requests==2.10.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/99/b4/63d99ba8e189c47d906b43bae18af4396e336f2b1bfec86af31efe2d2cb8/requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.8MB/s 
Collecting simplejson==3.8.2 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 3.1MB/s 
Collecting urllib3==1.20 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/67/87/67be08389f8df83c9ba4c12e618a4ad93546e234a1e9530618735cd9b73d/urllib3-1.20-py2.py3-none-any.whl (111kB)
    100% |████████████████████████████████| 112kB 3.0MB/s 
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/dist-packages (from pandas==0.19.2->-r requirements.txt (line 4)) (2018.5)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/dist-packages (from pandas==0.19.2->-r requirements.txt (line 4)) (2.6.1)
Building wheels for collected packages: simplejson
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/b0/2a/43/57bc8cc4565cda29e70b3a7a427d73f43d98fedb9ce1b1d00c
Successfully built simplejson
mitmproxy 0.18.2 requires click<7.0,>=6.2, which is not installed.
mitmproxy 0.18.2 requires lxml<=3.6.0,>=3.5.0, which is not installed.
shodan 1.7.7 requires click, which is not installed.
nyawc 1.8.1 requires beautifulsoup4==4.6.0, which is not installed.
nyawc 1.8.1 requires lxml==4.0.0, which is not installed.
mitmproxy 0.18.2 has requirement configargparse<0.12,>=0.10, but you'll have configargparse 0.13.0 which is incompatible.
mitmproxy 0.18.2 has requirement cryptography<1.6,>=1.3, but you'll have cryptography 2.1.4 which is incompatible.
mitmproxy 0.18.2 has requirement html2text<=2016.9.19,>=2016.1.8, but you'll have html2text 2018.1.9 which is incompatible.
mitmproxy 0.18.2 has requirement hyperframe<5,>=4.0.1, but you'll have hyperframe 5.1.0 which is incompatible.
mitmproxy 0.18.2 has requirement passlib<1.7,>=1.6.5, but you'll have passlib 1.7.1 which is incompatible.
mitmproxy 0.18.2 has requirement pyOpenSSL<17.0,>=16.0, but you'll have pyopenssl 17.5.0 which is incompatible.
mitmproxy 0.18.2 has requirement pyparsing<2.2,>=2.1.3, but you'll have pyparsing 2.2.0 which is incompatible.
mitmproxy 0.18.2 has requirement urwid<1.4,>=1.3.1, but you'll have urwid 2.0.1 which is incompatible.
dropbox 8.7.1 has requirement requests>=2.16.2, but you'll have requests 2.10.0 which is incompatible.
nyawc 1.8.1 has requirement requests==2.18.4, but you'll have requests 2.10.0 which is incompatible.
nosqlmap 0.7 has requirement requests==2.5.0, but you'll have requests 2.10.0 which is incompatible.
Installing collected packages: dnspython, fuzzywuzzy, numpy, requests, simplejson, urllib3
  Found existing installation: numpy 1.15.0
    Uninstalling numpy-1.15.0:
      Successfully uninstalled numpy-1.15.0
  Found existing installation: simplejson 3.15.0
Cannot uninstall 'simplejson'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
root@harris:~/GitHub/VHostScan# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    '' if num_installed else 'numpy==1.12.0'],
NameError: name 'num_installed' is not defined
root@harris:~/GitHub/VHostScan#

**Comment by codingo** [comment]
@harriseka, if you run VHostScan after this you see the first output? I'm unsure how to help at this point, it looks to me like everything is working.

Could you do:

```
VHostScan -t <target>
```

If  that doesn't work please reply here and I'll reopen this issue.
